from pathlib import Path
import zipfile,json
z=zipfile.ZipFile('C:/Users/gildo/temp/v4 test 2.zip');n=next(n for n in z.namelist() if '_062100_' in n);rs=[json.loads(l) for l in z.open(n)];r=next(r for r in rs if r['event']=='movement_cycle' and r.get('plannerEvent')=='fixed_destination_planned');print(r['surferDistanceM'])
s=Path('exports/vt403/snapshot_kml.py').read_text(encoding='utf-8-sig')
s=s.replace('_061049_','_062100_').replace('1791058369824','1791058913293')
s=s.replace('06:12:49.824','06:21:53.293').replace('06:12:49.775 (49 ms earlier)','06:21:53.293 (exact planning cycle)').replace('49 ms earlier','exact planning cycle')
s=s.replace('Sideways-right blocked geometry','Sideways-right ALLOWED alignment geometry')
s=s.replace('alignment destination that','alignment destination that')
s=s.replace('proposed alignment-only destination, never commanded','saved alignment-only destination, movement permitted')
s=s.replace('BLOCKED alignment destination','ALLOWED fixed alignment destination')
s=s.replace('11.91',f"{r['projectedSeparationM']:.2f}").replace('30.80',f"{abs(r['comeToMeAlignmentErrorM']):.2f}").replace('33.02',f"{r['surferDistanceM']:.2f}")
s=s.replace('Inside 18 m retreat radius. VT did not fly here.','Outside the 18 m retreat radius. VT started moving toward this fixed destination at 06:21:53.396.')
s=s.replace(' — BLOCKED',' — ALLOWED').replace('rejected alignment-only destination','allowed alignment-only destination')
s=s.replace('below 18 m retreat clearance','above 18 m retreat clearance').replace('P lies inside this circle.','P lies outside this circle.')
s=s.replace('This boundary was not the reason for the alignment block.','The retreat boundary does not constrain this Come-to-me journey.')
s=s.replace('right-061249-projection.kml','right-062153-allowed-projection.kml')
s=s.replace("('blocked','ff0000ff',5)","('blocked','ff00aa00',5),('clearance','ff0000ff',3)")
s=s.replace("for i in range(0,361,5)],'blocked'","for i in range(0,361,5)],'clearance'")
Path('exports/vt403/allowed_snapshot.py').write_text(s,encoding='utf-8')
